from app.domain.models import ScenarioDefinition

SCENARIOS = [
 ScenarioDefinition(id="scenario-01",name="Restricted-zone vehicle deviation and M17 anomaly",description="Forklift A enters a restricted zone before M17 telemetry and throughput degrade.",affected_entity_ids=["forklift-a","machine-m17"],affected_zone_ids=["restricted-zone-c","packaging-line"],sensor_kinds=["temperature","vibration","throughput"],expected_severity="critical",root_cause="vehicle/equipment interaction",alternative_hypotheses=["mechanical failure","sensor malfunction"]),
 ScenarioDefinition(id="scenario-02",name="Maintenance dwell",description="Worker remains in maintenance longer than expected.",affected_entity_ids=["worker-317"],affected_zone_ids=["maintenance-area"],sensor_kinds=["occupancy"],expected_severity="elevated",root_cause="unplanned maintenance activity",alternative_hypotheses=["access event delay"]),
 ScenarioDefinition(id="scenario-03",name="Machine telemetry anomaly",description="M17 temperature and vibration move outside operating ranges.",affected_entity_ids=["machine-m17"],affected_zone_ids=["packaging-line"],sensor_kinds=["temperature","vibration"],expected_severity="critical",root_cause="mechanical failure",alternative_hypotheses=["sensor malfunction"]),
 ScenarioDefinition(id="scenario-04",name="Unexpected nighttime movement",description="Vehicle movement occurs outside normal activity hours.",affected_entity_ids=["tugger-t01"],affected_zone_ids=["warehouse-a"],sensor_kinds=["access-control"],expected_severity="elevated",root_cause="unauthorized after-hours movement",alternative_hypotheses=["late shift exception"]),
 ScenarioDefinition(id="scenario-05",name="Vehicle route deviation",description="Forklift B uses an unexpected transition.",affected_entity_ids=["forklift-b"],affected_zone_ids=["restricted-zone-c"],sensor_kinds=["occupancy"],expected_severity="elevated",root_cause="route deviation",alternative_hypotheses=["temporary reroute"]),
 ScenarioDefinition(id="scenario-06",name="Congestion throughput degradation",description="Upstream congestion precedes conveyor throughput decline.",affected_entity_ids=["conveyor-c03","forklift-a"],affected_zone_ids=["warehouse-a","packaging-line"],sensor_kinds=["throughput","occupancy"],expected_severity="elevated",root_cause="upstream congestion",alternative_hypotheses=["conveyor fault"]),
 ScenarioDefinition(id="scenario-07",name="Noisy sensor spikes",description="A sensor produces repeated spikes that should be evaluated as false-positive-prone.",affected_entity_ids=["machine-m17"],affected_zone_ids=["packaging-line"],sensor_kinds=["temperature"],expected_severity="watch",root_cause="sensor malfunction",alternative_hypotheses=["transient heat variation"]),
 ScenarioDefinition(id="scenario-08",name="Safety-zone occupancy",description="Worker occupies a safety zone while M17 is active.",affected_entity_ids=["worker-204","machine-m17"],affected_zone_ids=["restricted-zone-c"],sensor_kinds=["occupancy","machine-state"],expected_severity="critical",root_cause="safety procedure violation",alternative_hypotheses=["sensor misread"]),
]
