"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Incident = { incident_id:string; title:string; severity:string; start_time:string; primary_zone_id:string; risk_score:number; leading_hypothesis:string; root_cause_confidence:number };
type Detail = { incident:Incident & {summary:string;recommendation:string}; timeline:{event_id:string;timestamp:string;event_type:string;entity_id:string}[]; evidence:{evidence_id:string;type:string;strength:string;summary:string}[]; hypotheses:{hypothesis_id:string;title:string;confidence:number;reason_summary:string;contradicting_evidence_ids:string[]}[]; graph:{nodes:unknown[];edges:{relationship_type:string;reason:string}[]} };
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export function IncidentCenter() {
  const [rows, setRows] = useState<Incident[]>([]); const [severity, setSeverity] = useState("");
  useEffect(() => { fetch(`${api}/incidents${severity ? `?severity=${severity}` : ""}`).then(r => r.json()).then(setRows).catch(() => setRows([])); }, [severity]);
  return <><header><p className="text-sm font-medium text-accent">Operational triage</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Incident center</h1><label className="mt-5 block text-sm font-medium">Severity <select className="ml-2 rounded border border-[var(--border)] bg-surface p-2" value={severity} onChange={e => setSeverity(e.target.value)}><option value="">All</option><option value="critical">Critical</option><option value="elevated">Elevated</option></select></label></header><div className="mt-7 overflow-x-auto rounded-lg border border-[var(--border)] bg-surface"><table className="min-w-full text-left text-sm"><thead className="border-b border-[var(--border)] text-muted"><tr><th className="p-4">Incident</th><th className="p-4">Severity</th><th className="p-4">Risk</th><th className="p-4">Leading hypothesis</th><th className="p-4">Confidence</th></tr></thead><tbody>{rows.map(row => <tr className="border-b border-[var(--border)] last:border-0" key={row.incident_id}><td className="p-4"><Link className="font-medium text-accent hover:underline" href={`/incidents/${row.incident_id}`}>{row.title}</Link><div className="mt-1 text-xs text-muted">{row.primary_zone_id} · {new Date(row.start_time).toLocaleString()}</div></td><td className="p-4 capitalize">{row.severity}</td><td className="p-4 tabular-nums">{row.risk_score}</td><td className="p-4">{row.leading_hypothesis}</td><td className="p-4 tabular-nums">{row.root_cause_confidence}%</td></tr>)}</tbody></table>{!rows.length && <p className="p-6 text-sm text-muted">No incidents match this filter. Clear the filter or reset the demo.</p>}</div></>;
}

export function IncidentDetail({ id }: { id:string }) {
  const [data, setData] = useState<Detail | null>(null); const [error, setError] = useState(false);
  useEffect(() => { setError(false); Promise.all(["", "/timeline", "/evidence", "/hypotheses", "/graph"].map(s => fetch(`${api}/incidents/${id}${s}`).then(r => r.ok ? r.json() : Promise.reject()))).then(([incident,timeline,evidence,hypotheses,graph]) => setData({incident,timeline,evidence,hypotheses,graph} as Detail)).catch(() => setError(true)); }, [id]);
  if (error) return <section className="rounded-lg border border-[var(--border)] bg-surface p-6"><h1 className="text-lg font-semibold">Unable to load this incident</h1><p className="mt-2 text-sm text-muted">Check that the API is running, then try again.</p><button className="mt-4 rounded bg-accent px-4 py-2 text-sm font-medium text-white" onClick={() => window.location.reload()}>Retry</button></section>;
  if (!data) return <p className="text-sm text-muted">Loading incident evidence…</p>;
  return <><Link className="text-sm text-accent hover:underline" href="/incidents">← Incident center</Link><header className="mt-5 rounded-lg border border-[var(--border)] bg-surface p-6"><p className="text-sm font-medium text-accent">{data.incident.severity} risk · {data.incident.risk_score}/100</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{data.incident.title}</h1><p className="mt-3 text-muted">{data.incident.summary}</p><p className="mt-4 text-sm"><strong>Recommended review:</strong> {data.incident.recommendation}</p></header><section className="mt-7 grid gap-6 lg:grid-cols-2"><Panel title="Timeline">{data.timeline.map(e => <p className="border-b border-[var(--border)] py-3 text-sm" key={e.event_id}>{new Date(e.timestamp).toLocaleTimeString()} · {e.event_type} · {e.entity_id}</p>)}</Panel><Panel title="Root-cause hypotheses">{data.hypotheses.map(h => <div className="border-b border-[var(--border)] py-3 text-sm" key={h.hypothesis_id}><p className="font-medium">{h.title} <span className="tabular-nums text-muted">{h.confidence}%</span></p><p className="mt-1 text-muted">{h.reason_summary}</p>{h.contradicting_evidence_ids.length > 0 && <p className="mt-1 text-danger">Counter-evidence is present.</p>}</div>)}</Panel><Panel title="Evidence">{data.evidence.map(e => <p className="border-b border-[var(--border)] py-3 text-sm" key={e.evidence_id}><strong className="capitalize">{e.type}</strong> · {e.strength}<br/><span className="text-muted">{e.summary}</span></p>)}</Panel><Panel title="Evidence graph"><p className="text-sm text-muted">{data.graph.nodes.length} nodes · {data.graph.edges.length} meaningful relationships</p><ul className="mt-3 space-y-2 text-sm">{data.graph.edges.map((e,i) => <li key={i}><strong>{e.relationship_type}</strong> — {e.reason}</li>)}</ul></Panel></section></>;
}
function Panel({title,children}:{title:string;children:React.ReactNode}) { return <section className="rounded-lg border border-[var(--border)] bg-surface p-5"><h2 className="text-lg font-semibold">{title}</h2><div className="mt-3">{children}</div></section>; }
