"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Incident = { incident_id:string; title:string; severity:string; start_time:string; primary_zone_id:string; risk_score:number; leading_hypothesis:string; root_cause_confidence:number };
type Detail = { incident:Incident & {summary:string;recommendation:string}; timeline:{event_id:string;timestamp:string;event_type:string;entity_id:string}[]; evidence:{evidence_id:string;type:string;strength:string;summary:string}[]; hypotheses:{hypothesis_id:string;title:string;confidence:number;reason_summary:string;contradicting_evidence_ids:string[]}[]; graph:{nodes:unknown[];edges:{relationship_type:string;reason:string}[]} };
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export function IncidentCenter() {
  const [rows, setRows] = useState<Incident[]>([]); const [severity, setSeverity] = useState("");
  useEffect(() => { fetch(`${api}/incidents${severity ? `?severity=${severity}` : ""}`).then(r => r.json()).then(setRows).catch(() => setRows([])); }, [severity]);
  return <><header className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Operational triage</p><h1 className="page-title mt-3">Focus the review where it matters.</h1><p className="page-copy mt-3 max-w-xl">Each incident joins related evidence into one reviewable thread. It is a prompt to investigate, never an autonomous decision.</p></div><label className="text-sm font-semibold">Show<select className="mt-2 block min-h-11 rounded-lg border border-[var(--border-strong)] bg-[var(--surface)] px-3 py-2 font-normal" value={severity} onChange={e => setSeverity(e.target.value)}><option value="">All incidents</option><option value="critical">Critical only</option><option value="elevated">Elevated only</option></select></label></header><div className="surface-card mt-8 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-[var(--border)] bg-[var(--canvas)] text-xs uppercase tracking-[.08em] text-muted"><tr><th className="p-4 font-semibold">Incident</th><th className="p-4 font-semibold">Severity</th><th className="p-4 font-semibold">Risk</th><th className="p-4 font-semibold">Leading hypothesis</th><th className="p-4 font-semibold">Confidence</th></tr></thead><tbody>{rows.map(row => <tr className="border-b border-[var(--border)] last:border-0 hover:bg-[rgb(244_241_234_/_0.55)]" key={row.incident_id}><td className="p-4"><Link className="font-semibold text-[var(--accent-deep)] hover:underline" href={`/incidents/${row.incident_id}`}>{row.title}</Link><div className="mt-1 text-xs text-muted">{row.primary_zone_id} · {new Date(row.start_time).toLocaleString()}</div></td><td className="p-4"><span className={`rounded-full px-2 py-1 text-xs font-semibold capitalize ${row.severity==="critical"?"bg-[#f7e5e2] text-danger":"bg-[var(--accent-soft)] text-[var(--accent-deep)]"}`}>{row.severity}</span></td><td className="metric-value p-4 font-semibold">{row.risk_score}</td><td className="p-4">{row.leading_hypothesis}</td><td className="metric-value p-4">{row.root_cause_confidence}%</td></tr>)}</tbody></table>{!rows.length && <p className="p-6 text-sm text-muted">No incidents match this view. Select a different filter or reset the demo.</p>}</div></>;
}

export function IncidentDetail({ id }: { id:string }) {
  const [data, setData] = useState<Detail | null>(null); const [error, setError] = useState(false);
  useEffect(() => { setError(false); Promise.all(["", "/timeline", "/evidence", "/hypotheses", "/graph"].map(s => fetch(`${api}/incidents/${id}${s}`).then(r => r.ok ? r.json() : Promise.reject()))).then(([incident,timeline,evidence,hypotheses,graph]) => setData({incident,timeline,evidence,hypotheses,graph} as Detail)).catch(() => setError(true)); }, [id]);
  if (error) return <section className="surface-card p-6"><h1 className="section-title">Unable to load this incident</h1><p className="page-copy mt-2 text-sm">Check that the API is available, then try again.</p><button className="button-primary mt-4" onClick={() => window.location.reload()}>Retry</button></section>;
  if (!data) return <p className="text-sm text-muted">Loading incident evidence…</p>;
  return <><Link className="text-sm font-semibold text-[var(--accent-deep)] hover:underline" href="/incidents">← Back to incident review</Link><header className="surface-card mt-5 border-l-4 border-l-[var(--danger)] p-6"><p className="eyebrow text-danger">{data.incident.severity} risk · {data.incident.risk_score}/100</p><h1 className="page-title mt-3">{data.incident.title}</h1><p className="page-copy mt-4 max-w-3xl">{data.incident.summary}</p><p className="mt-5 rounded-lg bg-[var(--canvas)] p-4 text-sm leading-6"><strong>Recommended review</strong><br/>{data.incident.recommendation}</p></header><section className="mt-7 grid gap-5 lg:grid-cols-2"><Panel title="Timeline">{data.timeline.map(e => <p className="border-b border-[var(--border)] py-3 text-sm last:border-0" key={e.event_id}><span className="font-medium">{e.event_type}</span><span className="text-muted"> · {e.entity_id}</span><span className="mt-1 block text-xs text-muted">{new Date(e.timestamp).toLocaleTimeString()}</span></p>)}</Panel><Panel title="Competing hypotheses">{data.hypotheses.map(h => <div className="border-b border-[var(--border)] py-3 text-sm last:border-0" key={h.hypothesis_id}><p className="font-semibold">{h.title} <span className="metric-value text-muted">{h.confidence}%</span></p><p className="mt-1 leading-6 text-muted">{h.reason_summary}</p>{h.contradicting_evidence_ids.length > 0 && <p className="mt-2 font-medium text-danger">Counter-evidence is present.</p>}</div>)}</Panel><Panel title="Evidence">{data.evidence.map(e => <p className="border-b border-[var(--border)] py-3 text-sm last:border-0" key={e.evidence_id}><strong className="capitalize">{e.type}</strong> · {e.strength}<br/><span className="mt-1 block leading-6 text-muted">{e.summary}</span></p>)}</Panel><Panel title="Evidence graph"><p className="text-sm leading-6 text-muted">{data.graph.nodes.length} nodes · {data.graph.edges.length} meaningful relationships</p><ul className="mt-4 space-y-3 text-sm">{data.graph.edges.map((e,i) => <li className="border-l-2 border-[var(--accent)] pl-3" key={i}><strong>{e.relationship_type}</strong><span className="mt-1 block text-muted">{e.reason}</span></li>)}</ul></Panel></section></>;
}
function Panel({title,children}:{title:string;children:React.ReactNode}) { return <section className="surface-card p-6"><h2 className="section-title">{title}</h2><div className="mt-4">{children}</div></section>; }
